### ISSUE TITLE
I can't run these in GPU

### ISSUE THREAD

**Issue by yellowjs0304** [ronghanghu/speaker_follower#10]
Hi, when I run your code, I found it used very little memory of GPU.
I ran `python tasks/R2R/train.py --use_pretraining --pretrain_splits train literal_speaker_data_augmentation_paths` in 1080ti and 1060 GPU.
But it doesn't.

So, I changed the command into `CUDA_VISIBLE_DEVICES=2 python tasks/R2R/train.py --use_pretraining --pretrain_splits train literal_speaker_data_augmentation_paths ` But I can't.

![capture](https://user-images.githubusercontent.com/30281608/48178623-04b1eb00-e35e-11e8-8f7e-71b1a2ae79ef.PNG)

What can I do? 
Thank you

**Comment by ronghanghu** [comment]
The codebase actually does use GPU. However, the majority amount of training time is actually spent upon getting observations from the M3D simulator, so the displayed gpu utilization percentage is quite low.
