### ISSUE TITLE
Precomputed ResNet Image Features File not found

### ISSUE THREAD

**Issue by parulaggarwal** [ronghanghu/speaker_follower#19]
@ronghanghu On running the below command I get a 404 Not Found error. Can you please update the link if it is still possible: 

`wget https://www.dropbox.com/s/715bbj8yjz32ekf/ResNet-152-imagenet.zip?dl=1 -O ResNet-152-imagenet.zip
`

**Comment by ronghanghu** [comment]
Hi, the Room-to-Room dataset recently changed the feature download location (which can be found on https://github.com/peteanderson80/Matterport3DSimulator#precomputing-resnet-image-features) to `https://www.dropbox.com/s/o57kxh2mn5rkx4o/ResNet-152-imagenet.zip?dl=1`.

Please use this new URL instead:
```
wget https://www.dropbox.com/s/o57kxh2mn5rkx4o/ResNet-152-imagenet.zip?dl=1 -O ResNet-152-imagenet.zip
```

**Comment by parulaggarwal** [comment]
Thanks for your response.
