### ISSUE TITLE
how to get the results by simulator?

### ISSUE THREAD

**Issue by yellowjs0304** [ronghanghu/speaker_follower#2]
Hi, Is there any way to get result on Simulator(or image based)?
I can't judge the result only by the text.

How can you get the images(Fig 4. Navigation example. etc) in your paper?

**Comment by ronghanghu** [comment]
The output files from `python tasks/R2R/rational_follower.py` contains the predicted trajectories, and you can visualize these trajectories in output files with the simulator.
