### ISSUE TITLE
Both the augmentation data and pre-trained models cannot been found now.

### ISSUE THREAD

**Issue by CrystalSixone** [ronghanghu/speaker_follower#24]
Hi,
Thanks for your awesome idea and work, and I want to download your augmentation data and the pre-trained models of the follower and the speaker, but both the links show that they cannot found now. Can you provide some new available download links?
![Selection_013](https://user-images.githubusercontent.com/44516327/130562117-a166bee3-8997-4ad4-84ac-2dd49fbe5d86.png)
![Selection_014](https://user-images.githubusercontent.com/44516327/130562133-cc4f7fb8-8414-4e6b-97c4-7f68f35d7b51.png)

Best wishes,
Crystal

**Comment by ronghanghu** [comment]
Hi, I've uploaded the trained models and the augmented data here: https://drive.google.com/drive/folders/1yCzG3g9vPlatFWokJbxZp8nWuN-xCNLW

Hope it helps!

**Comment by CrystalSixone** [comment]
> Hi, I've uploaded the trained models and the augmented data here: https://drive.google.com/drive/folders/1yCzG3g9vPlatFWokJbxZp8nWuN-xCNLW
> 
> Hope it helps!

Thanks a lot!
