### ISSUE TITLE
Multiple-GPU support

### ISSUE THREAD

**Issue by zwx8981** [ronghanghu/speaker_follower#3]
Hi, thank you for sharing your great works.  You mentioned in ReadMe that all the commands above run on a single GPU, so I am just wondering do you support training on multiple gpus right now?

**Comment by ronghanghu** [comment]
So far, the codebase multi-GPU training hasn't been implemented yet. The codebase is largely built upon the [Matterport3DSimulator](https://github.com/peteanderson80/Matterport3DSimulator) codebase that only runs on a single GPU.
