### ISSUE TITLE
Out of CUDA memory problem during inference process.

### ISSUE THREAD

**Issue by zwx8981** [ronghanghu/speaker_follower#4]
I use a single GTX 1080TI with 11GB memory and I meet the problem of out of CUDA memory with your default setting during the second step of inference. Is there any quick fix for this problem?(such as reducing batch size?) Thank you.

**Comment by ronghanghu** [comment]
You can try a smaller batch size number in `--batch_size`, such as `--batch_size 10`.

(Note that we used batch size 15 on a TitanXp GPU.)
