### ISSUE TITLE
Using the closest loc makes the action selection a little easier.

### ISSUE THREAD

**Issue by cswhjiang** [ronghanghu/speaker_follower#6]
It seems that if there are multiple locations with the same viewpoint, only one is selected when testing. This makes the action selection a little easier.

https://github.com/ronghanghu/speaker_follower/blob/master/tasks/R2R/env.py#L195

**Comment by ronghanghu** [comment]
Hi, I'm not sure whether I correctly understood your question. In our implementation, **all** navigable directions are preserved and can be selected at test time. If there are multiple navigable directions `j_1` and `j_2` within the same viewpoint, both `j_1` and `j_2` are preserved and can be selected by the agent.

The highlighted code https://github.com/ronghanghu/speaker_follower/blob/master/tasks/R2R/env.py#L195 means that j1 will use the *visual features from the closest viewpoint* as its appearance representation.

**Comment by cswhjiang** [comment]
The dimension of  ```all_u_t``` (https://github.com/ronghanghu/speaker_follower/blob/master/tasks/R2R/follower.py#L470) is ```100 x N x 2176``` and ```N``` is a number smaller than 36. So, you assume the agent knows that relationship between the 36 views and adjacency viewpoints. And the agent actually selects viewpoint, not view.  Is  my understanding correct?

**Comment by ronghanghu** [comment]
Yes, we select from one of the possible `N` directions to go next. These `N` directions are observations that the agent obtains from the environment (the simulator's state).

We note that N is not necessarily less than the number of viewpoints, also the setting of 36 discrete views is mostly a choice in the baseline agent, but not the environment (the simulator actually supports continuous views).

**Comment by cswhjiang** [comment]
> If there are multiple navigable directions j_1 and j_2 within the same viewpoint, both j_1 and j_2 are preserved and can be selected by the agent.

>  j1 will use the visual features from the closest viewpoint as its appearance representation

Assume that j_1 and j_2 are two navigable directions selected from the 36 directions, j_1 and j_2 have the same viewpoint, and j_2 has smaller distance. According to the [```_get_panorama_states ```](https://github.com/ronghanghu/speaker_follower/blob/master/tasks/R2R/env.py#L149) function in ``` env.py ```, it seems that only j_2 can be selected.

**Comment by ronghanghu** [comment]
No, it only means that j_1 and j_2 will use the same closest view's *image features* as its visual appearance representation. On the other hand, j_1 and j_2 still different representation in there angle/direction (their `sin(theta)`, `cos(theta)`, `sin(phi)` and `cos(phi)` in `_build_action_embedding` in https://github.com/ronghanghu/speaker_follower/blob/master/tasks/R2R/env.py#L69-L74.

Note that both j_1 and j_2 will be availabe for the agent to choose from, and only a part of their representation (the appearance features) will be the same. Their angle features (`sin(theta)`, `cos(theta)`, `sin(phi)` and `cos(phi)`) will be different.

**Comment by cswhjiang** [comment]
Let's see an example. 
Here is the view indices and the corresponding navigableLocations:
```
0:
1:
2:
3:
4: 5a829e63cd8b4ba1aa176297ac85d376
5: 5a829e63cd8b4ba1aa176297ac85d376 d57d0493cc9b4db18e027a9777805255
6: b27d2a3779c1416380a8c66f1ad3d32a d57d0493cc9b4db18e027a9777805255 5a829e63cd8b4ba1aa176297ac85d376
7: b27d2a3779c1416380a8c66f1ad3d32a
8:
9:
10:
11:
12:
13:
14:
15:
16: 5a829e63cd8b4ba1aa176297ac85d376
17: 5a829e63cd8b4ba1aa176297ac85d376 d57d0493cc9b4db18e027a9777805255
18: b27d2a3779c1416380a8c66f1ad3d32a d57d0493cc9b4db18e027a9777805255 5a829e63cd8b4ba1aa176297ac85d376
19: b27d2a3779c1416380a8c66f1ad3d32a
20:
21:
22:
23:
24:
25:
26:
27:
28: 5a829e63cd8b4ba1aa176297ac85d376
29: 5a829e63cd8b4ba1aa176297ac85d376 d57d0493cc9b4db18e027a9777805255
30: d57d0493cc9b4db18e027a9777805255 b27d2a3779c1416380a8c66f1ad3d32a 5a829e63cd8b4ba1aa176297ac85d376
31: b27d2a3779c1416380a8c66f1ad3d32a
32:
33:
34:
35:
```
Here is the adj_loc_list:
```
[
{'absViewIndex': -1, 'nextViewpointId': '7f0e99a1c2e2471ea41d91cf7acdb770'}, 
{'absViewIndex': 17, 'nextViewpointId': '5a829e63cd8b4ba1aa176297ac85d376', 'rel_heading': 2.474595648633056, 'rel_elevation': 0.008478405097333962, 'distance': 0.14364865309542466}, {'absViewIndex': 18, 'nextViewpointId': 'd57d0493cc9b4db18e027a9777805255', 'rel_heading': 2.880360055795774, 'rel_elevation': 0.006110138818764544, 'distance': 0.26130404502532384}, {'absViewIndex': 18, 'nextViewpointId': 'b27d2a3779c1416380a8c66f1ad3d32a', 'rel_heading': -2.932759203343438, 'rel_elevation': -0.027173948070545434, 'distance': 0.21059400132847472}]
```

Hence, the view 4, 5, 6, 7, 16, 17, 18, 19, 28, 29, 30, 31 are navigable. In your implementation, only four navigable viewpoints can be selected, which are 7f0e99a1c2e2471ea41d91cf7acdb770, 5a829e63cd8b4ba1aa176297ac85d376, d57d0493cc9b4db18e027a9777805255, b27d2a3779c1416380a8c66f1ad3d32a.

Therefore, the agent selects the viewpoints, not views. And the number of navigable views is usually is larger than the number of navigable viewpoints. Hence, it makes the action space smaller.

**Comment by ronghanghu** [comment]
I see what you mean. In our model, the agent chooses from one of the 4 navigable directions in 
```
[
{'absViewIndex': -1, 'nextViewpointId': '7f0e99a1c2e2471ea41d91cf7acdb770'}, 
{'absViewIndex': 17, 'nextViewpointId': '5a829e63cd8b4ba1aa176297ac85d376', 'rel_heading': 2.474595648633056, 'rel_elevation': 0.008478405097333962, 'distance': 0.14364865309542466}, 
{'absViewIndex': 18, 'nextViewpointId': 'd57d0493cc9b4db18e027a9777805255', 'rel_heading': 2.880360055795774, 'rel_elevation': 0.006110138818764544, 'distance': 0.26130404502532384}, 
{'absViewIndex': 18, 'nextViewpointId': 'b27d2a3779c1416380a8c66f1ad3d32a', 'rel_heading': -2.932759203343438, 'rel_elevation': -0.027173948070545434, 'distance': 0.21059400132847472}
]
```
(where the 1st one corresponds to the `STOP` action). The agent will score these 4 choices and pick the highest scoring one. The agent does not select one of {4,5,6,7,16,17,18,19,28,29,30,31} views, nor one of the 36 views.

At this location, the agent can observe (from `state.state.navigableLocations`) that there are 4 possible next locations it can go next (including staying still and stop). It will score and choose from these 4 options.
