### ISSUE TITLE
Is the downloadable follower model trained using the default setting?

### ISSUE THREAD

**Issue by littlekobe** [ronghanghu/speaker_follower#7]
Hi, thanks for the nice code.

I am wondering if the follower model downloaded using `./tasks/R2R/snapshots/release/download_follower_release.sh` can be trained using the default settings. If not, what are the settings? Thanks!

**Comment by ronghanghu** [comment]
Yes, it should be trainable using the default setting.

Note that for test set evaluation and challenge submission, we picked the iteration corresponding to the highest success rate on `val_unseen` split (the highest success rate snapshot is automatically tracked and marked with a special filename containing `val_unseen-success_rate=`).

**Comment by littlekobe** [comment]
Thanks for your quick response, @ronghanghu!
